name: Remote Android Build

on:
  push:
    branches:
      - main  # Automatically triggers whenever code changes on main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew
        working-directory: DigitalSilhouette

      - name: Build Release APK
        run: ./gradlew assembleRelease
        working-directory: DigitalSilhouette

      - name: Upload APK to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: Kinetix-Remote-Build
          path: DigitalSilhouette/app/build/outputs/apk/release/*.apk
